// Code generated by "go generate neoyagami/gonum/unit/constant”; DO NOT EDIT.

// Copyright ©2019 The Gonum Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package constant

import "neoyagami/gonum/unit"

// ElementaryCharge, is the elementary charge constant (e), the magnitude of electric charge carried by a single proton or electron.
// The dimensions of ElementaryCharge are A s. The constant is exact.
const ElementaryCharge = unit.Charge(1.602176634e-19)
